In [1]:
!python ml_pipeline.py

In [2]:
import os
import joblib
from ml_pipeline import run_target_pipeline
current_path = os.getcwd()+"\\models"

# higher propensity to buy a mutal fund

In [3]:
ranking_mf_df, model_mf = run_target_pipeline("Sale_MF", "Prob_Purchase_MF")
joblib.dump(model_mf, os.path.join(current_path, 'model_mf.pkl'))
ranking_mf_df = ranking_mf_df.sort_values(by='Prob_Purchase_MF', ascending=False)
# select top N clients
top_15_percent_mf = int(0.15*len(ranking_mf_df))
ranking_mf_df.head(20)

Current folder: D:\llm-engineering-projects\llm_engineering\singlife-assesment\data\DataScientist_CaseStudy_Dataset.xlsx
soc_dem_df counts: 1615
products_bal_df counts: 1615
inflow_outflow_df counts: 1587
sales_revenues_df counts: 969
1615 rows in the source data frame
 X_train lenght is : 678
 X_test lenght is : 291
 y_train lenght is : 678
 y_test lenght is : 291
 ******  training done ****

      Client  Prob_Purchase_MF
531     1261              0.87
783     1564              0.76
493     1565              0.76
191      436              0.68
1476    1382              0.68
474     1059              0.67
1063     802              0.67
442      970              0.66
433     1581              0.66
940       75              0.64
605      874              0.63
1095    1143              0.63
346      649              0.61
229     1294              0.59
578     1325              0.59
990      777              0.59
457     1462              0.57
1199     746              0.56
36       682              0.55
1434    1233              0.55

# higher propensity to buy a credit card

In [11]:
# For Credit Card
ranking_cc_df, model_cc = run_target_pipeline('Sale_CC', 'Prob_Purchase_CC')
joblib.dump(model_cc, os.path.join(current_path, 'model_cc.pkl'))
ranking_cc_df = ranking_cc_df.sort_values(by='Prob_Purchase_CC', ascending=False)
# select top N clients
top_15_percent_cc = int(0.15*len(ranking_cc_df))
ranking_cc_df.head(20)

Current folder: D:\llm-engineering-projects\llm_engineering\singlife-assesment\DataScientist_CaseStudy_Dataset.xlsx
soc_dem_df counts: 1615
products_bal_df counts: 1615
inflow_outflow_df counts: 1587
sales_revenues_df counts: 969
1615 rows in the source data frame
 X_train lenght is : 678
 X_test lenght is : 291
 y_train lenght is : 678
 y_test lenght is : 291
 ******  training done ****

      Client  Prob_Purchase_CC
1276     529              0.82
617      385              0.82
748      942              0.77
1504     822              0.75
1580     963              0.75
509      420              0.75
205     1303              0.74
305     1078              0.73
602       21              0.72
202     1165              0.68
1568     694              0.68
713      219              0.63
794       68              0.63
870     1330              0.62
1422     610              0.60
366      372              0.60
581     1220              0.60
155      215              0.58
494       65              0.58
705      917              0.57

In [12]:
# higher propensity to buy a consumer load

In [13]:
# For Consumer Loan
ranking_cl_df, model_cl = run_target_pipeline('Sale_CL', 'Prob_Purchase_CL')
joblib.dump(model_cl, os.path.join(current_path, 'model_cl.pkl'))
ranking_cl_df = ranking_cl_df.sort_values(by='Prob_Purchase_CL', ascending=False)
# select top N clients
top_15_percent_cl = int(0.15*len(ranking_cl_df))
ranking_cl_df.head(20)

Current folder: D:\llm-engineering-projects\llm_engineering\singlife-assesment\DataScientist_CaseStudy_Dataset.xlsx
soc_dem_df counts: 1615
products_bal_df counts: 1615
inflow_outflow_df counts: 1587
sales_revenues_df counts: 969
1615 rows in the source data frame
 X_train lenght is : 678
 X_test lenght is : 291
 y_train lenght is : 678
 y_test lenght is : 291
 ******  training done ****

      Client  Prob_Purchase_CL
798      438              0.83
18       316              0.81
1148    1524              0.79
36       682              0.77
8       1231              0.77
1476    1382              0.76
464      995              0.75
625      557              0.74
889      288              0.74
1083    1409              0.73
1361     212              0.73
82       248              0.71
785      845              0.71
662     1159              0.70
576     1175              0.68
1207    1463              0.67
1451     775              0.66
681     1308              0.65
369     1109              0.63
825      365              0.63

# Expected Value (EV) Calculation

# EV = Propensity × Expected Revenue

# sample 

Client ID	EV_Loan	EV_Card	EV_MF	Best Offer	Max EV


A0001	    544	     240	240	     Loan	     544